services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///prefect.db"
    volumes:
      - prefect_data:/root/.prefect



  pipeline-runner:
    build:
      context: .
      dockerfile: /Dockerfile
    container_name: pipeline-runner
    depends_on:
      - postgres
      - minio
      - prefect-server
    command: uv run python prefect_scrap/src/pipeline/main.py
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: scraper
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_HOST: minio
      MINIO_PORT: "9000"
volumes:
  postgres_data:
  minio_data:
  prefect_data:
